-- Casts/cleans staging_311_requests (all TEXT) into raw_311_requests.
-- Run after a COPY into staging. Safe to run repeatedly: ON CONFLICT makes
-- it idempotent, so a rerun after a partial/interrupted load just re-applies
-- the same rows without duplicating or erroring.
INSERT INTO raw_311_requests (
    unique_key, created_date, closed_date, agency, agency_name,
    complaint_type, descriptor, additional_details, location_type,
    incident_zip, incident_address, street_name, cross_street_1, cross_street_2,
    intersection_street_1, intersection_street_2, address_type, city, landmark,
    facility_type, status, due_date, resolution_description, resolution_updated_date,
    community_board, council_district, police_precinct, bbl, borough,
    x_coordinate, y_coordinate, channel_type, park_facility_name, park_borough,
    vehicle_type, taxi_company_borough, taxi_pickup_location, bridge_highway_name,
    bridge_highway_direction, road_ramp, bridge_highway_segment, latitude, longitude,
    source
)
SELECT
    NULLIF(unique_key, '')::BIGINT,
    NULLIF(created_date, '')::TIMESTAMP,
    NULLIF(closed_date, '')::TIMESTAMP,
    NULLIF(agency, ''),
    NULLIF(agency_name, ''),
    NULLIF(complaint_type, ''),
    NULLIF(descriptor, ''),
    NULLIF(additional_details, ''),
    NULLIF(location_type, ''),
    NULLIF(incident_zip, ''),
    NULLIF(incident_address, ''),
    NULLIF(street_name, ''),
    NULLIF(cross_street_1, ''),
    NULLIF(cross_street_2, ''),
    NULLIF(intersection_street_1, ''),
    NULLIF(intersection_street_2, ''),
    NULLIF(address_type, ''),
    NULLIF(city, ''),
    NULLIF(landmark, ''),
    NULLIF(facility_type, ''),
    NULLIF(status, ''),
    NULLIF(due_date, '')::TIMESTAMP,
    NULLIF(resolution_description, ''),
    NULLIF(resolution_updated_date, '')::TIMESTAMP,
    NULLIF(community_board, ''),
    NULLIF(council_district, ''),
    NULLIF(police_precinct, ''),
    NULLIF(bbl, ''),
    NULLIF(borough, ''),
    -- Thousands-separator commas ("1,046,550") make these invalid numeric
    -- literals until stripped.
    NULLIF(REPLACE(x_coordinate, ',', ''), '')::DOUBLE PRECISION,
    NULLIF(REPLACE(y_coordinate, ',', ''), '')::DOUBLE PRECISION,
    NULLIF(channel_type, ''),
    NULLIF(park_facility_name, ''),
    NULLIF(park_borough, ''),
    NULLIF(vehicle_type, ''),
    NULLIF(taxi_company_borough, ''),
    NULLIF(taxi_pickup_location, ''),
    NULLIF(bridge_highway_name, ''),
    NULLIF(bridge_highway_direction, ''),
    NULLIF(road_ramp, ''),
    NULLIF(bridge_highway_segment, ''),
    NULLIF(latitude, '')::DOUBLE PRECISION,
    NULLIF(longitude, '')::DOUBLE PRECISION,
    %(source)s
FROM staging_311_requests
WHERE NULLIF(unique_key, '') IS NOT NULL
ON CONFLICT (unique_key) DO UPDATE SET
    created_date = EXCLUDED.created_date,
    closed_date = EXCLUDED.closed_date,
    agency = EXCLUDED.agency,
    agency_name = EXCLUDED.agency_name,
    complaint_type = EXCLUDED.complaint_type,
    descriptor = EXCLUDED.descriptor,
    additional_details = EXCLUDED.additional_details,
    location_type = EXCLUDED.location_type,
    incident_zip = EXCLUDED.incident_zip,
    incident_address = EXCLUDED.incident_address,
    street_name = EXCLUDED.street_name,
    cross_street_1 = EXCLUDED.cross_street_1,
    cross_street_2 = EXCLUDED.cross_street_2,
    intersection_street_1 = EXCLUDED.intersection_street_1,
    intersection_street_2 = EXCLUDED.intersection_street_2,
    address_type = EXCLUDED.address_type,
    city = EXCLUDED.city,
    landmark = EXCLUDED.landmark,
    facility_type = EXCLUDED.facility_type,
    status = EXCLUDED.status,
    due_date = EXCLUDED.due_date,
    resolution_description = EXCLUDED.resolution_description,
    resolution_updated_date = EXCLUDED.resolution_updated_date,
    community_board = EXCLUDED.community_board,
    council_district = EXCLUDED.council_district,
    police_precinct = EXCLUDED.police_precinct,
    bbl = EXCLUDED.bbl,
    borough = EXCLUDED.borough,
    x_coordinate = EXCLUDED.x_coordinate,
    y_coordinate = EXCLUDED.y_coordinate,
    channel_type = EXCLUDED.channel_type,
    park_facility_name = EXCLUDED.park_facility_name,
    park_borough = EXCLUDED.park_borough,
    vehicle_type = EXCLUDED.vehicle_type,
    taxi_company_borough = EXCLUDED.taxi_company_borough,
    taxi_pickup_location = EXCLUDED.taxi_pickup_location,
    bridge_highway_name = EXCLUDED.bridge_highway_name,
    bridge_highway_direction = EXCLUDED.bridge_highway_direction,
    road_ramp = EXCLUDED.road_ramp,
    bridge_highway_segment = EXCLUDED.bridge_highway_segment,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude;
